name: Build & Test

on:
  push:
    tags-ignore: v*.*
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: init
        run: |
          sudo apt install -yqq ninja-build xorg-dev g++-12
          sudo apt-get install xorg-dev libglu1-mesa-dev
      - name: configure gcc
        run: cmake -S . -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-12 -B plain_build
      - name: build gcc
        run: cmake --build plain_build
      - name: test
        run: cd build && ctest
